### ISSUE TITLE
비율이 고무줄처럼 늘어났다가줄어들었다가늘어났다가줄어들었다가늘어났다가줄어들었다가

### ISSUE THREAD

**Issue by lky473736** [xEzIxX/xEzIxX#1]
<img width="582" alt="스크린샷 2024-09-16 오후 6 59 12" src="https://github.com/user-attachments/assets/542f2d71-dfc8-4faa-aab7-86101105051c">

고양이가 프로필에 있는 각 테크 버튼의 비율을 수정해달라고 울어요
아마도 각 칸의 width를 조금 늘려보심이 어떠신가 싶어요

**Comment by xEzIxX** [comment]
@lky473736 수정했구리!! 😼

**Comment by lky473736** [comment]
LGTM
